'use client';

import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Head() {
    return (
        <>
            <title>Pokemon Team Builder</title>
            <meta
                content="width=device-width, initial-scale=1"
                name="viewport"
            />
            <meta name="description" content="Generated by create next app" />
            <style jsx global>{`
                html {
                    font-family: ${inter.fontFamily};
                }
            `}</style>
            <link rel="icon" href="/favicon.ico" />
        </>
    );
}
